# Generated by Django 4.0.4 on 2022-06-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='count_students',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='reviews',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='short_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
