# Generated by Django 4.0.4 on 2022-06-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_courses_category_alter_courses_comments_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_title', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='upload')),
            ],
        ),
    ]
