# Generated by Django 4.0.4 on 2022-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_onlinecourses_min_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='upload')),
                ('percent', models.IntegerField(default=0)),
                ('short_description', models.TextField()),
                ('info1', models.CharField(max_length=300)),
                ('info2', models.CharField(max_length=300)),
                ('info3', models.CharField(max_length=300)),
            ],
        ),
    ]
