# Generated by Django 4.0.4 on 2022-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo2',
            field=models.ImageField(default='', upload_to='upload'),
        ),
    ]
