# Generated by Django 4.0.4 on 2022-06-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutus_logo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='minutes',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
