# Generated by Django 4.0.4 on 2022-06-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_courses_hours_int_courses_minutes_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author_text',
            field=models.TextField(blank=True),
        ),
    ]
