# Generated by Django 4.0.4 on 2022-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_author_name_alter_blog_author_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='logo3_header',
            field=models.ImageField(default='', upload_to='upload'),
        ),
    ]
