# Generated by Django 4.0.4 on 2022-06-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_aboutus_logo3_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='logo_author',
            field=models.ImageField(default='', upload_to='upload'),
        ),
    ]
