# Generated by Django 4.0.4 on 2022-06-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='logo_author',
            field=models.ImageField(blank=True, default='', upload_to='upload'),
        ),
    ]
