# Generated by Django 4.0.4 on 2022-06-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blog_logo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='logo_recent',
            field=models.ImageField(blank=True, default='', upload_to='upload'),
        ),
    ]
