# Generated by Django 4.0.4 on 2022-06-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_blog_logo_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='info1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='info2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='info3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='info4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='logo1',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='logo2',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='plus_post_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
