# Generated by Django 4.0.4 on 2022-06-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
    ]
