# Generated by Django 4.0.4 on 2022-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
