# Generated by Django 4.0.4 on 2022-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_comment_email_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='info4',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='info5',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='info6',
            field=models.CharField(default='', max_length=300),
        ),
    ]
