# Generated by Django 4.0.4 on 2022-06-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_aboutus_info4_aboutus_info5_aboutus_info6'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=300)),
                ('subjects', models.CharField(max_length=300)),
                ('subjects_title', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=300)),
                ('course_title', models.CharField(max_length=300)),
                ('teachers', models.CharField(max_length=300)),
                ('teachers_title', models.CharField(max_length=300)),
                ('testimonial', models.CharField(max_length=300)),
                ('testimonial_title', models.CharField(max_length=300)),
                ('our_blog', models.CharField(max_length=300)),
                ('our_blog_title', models.CharField(max_length=300)),
                ('domain_name', models.CharField(max_length=300)),
                ('my_site', models.CharField(max_length=300)),
            ],
        ),
    ]
