# Generated by Django 4.0.4 on 2022-06-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_signupforcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnewinfo',
            name='newsletter_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='addnewinfo',
            name='newsletter_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
