# Generated by Django 4.0.4 on 2022-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_teachers_instagram_teachers_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='twitter',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
