# Generated by Django 4.0.4 on 2022-06-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_teachers_facebook_alter_teachers_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
