# Generated by Django 4.0.4 on 2022-06-19 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_feedbackmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='profession_foreign',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
