# Generated by Django 4.0.4 on 2022-06-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_contact_facebook_alter_contact_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='logo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
